<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        // Define the list of countries with their continent IDs
        // Continent IDs: AF (Africa), AS (Asia), EU (Europe), NA (North America), OC (Oceania), SA (South America)
        $countries = [
            ['name' => 'Afghanistan', 'continent_id' => 'AS'],
            ['name' => 'Albania', 'continent_id' => 'EU'],
            ['name' => 'Algeria', 'continent_id' => 'AF'],
            ['name' => 'Andorra', 'continent_id' => 'EU'],
            ['name' => 'Angola', 'continent_id' => 'AF'],
            ['name' => 'Argentina', 'continent_id' => 'SA'],
            ['name' => 'Armenia', 'continent_id' => 'AS'],
            ['name' => 'Australia', 'continent_id' => 'OC'],
            ['name' => 'Austria', 'continent_id' => 'EU'],
            ['name' => 'Azerbaijan', 'continent_id' => 'AS'],
            ['name' => 'Bahamas', 'continent_id' => 'NA'],
            ['name' => 'Bahrain', 'continent_id' => 'AS'],
            ['name' => 'Bangladesh', 'continent_id' => 'AS'],
            ['name' => 'Barbados', 'continent_id' => 'NA'],
            ['name' => 'Belarus', 'continent_id' => 'EU'],
            ['name' => 'Belgium', 'continent_id' => 'EU'],
            ['name' => 'Belize', 'continent_id' => 'NA'],
            ['name' => 'Benin', 'continent_id' => 'AF'],
            ['name' => 'Bhutan', 'continent_id' => 'AS'],
            ['name' => 'Bolivia', 'continent_id' => 'SA'],
            ['name' => 'Bosnia and Herzegovina', 'continent_id' => 'EU'],
            ['name' => 'Botswana', 'continent_id' => 'AF'],
            ['name' => 'Brazil', 'continent_id' => 'SA'],
            ['name' => 'Brunei', 'continent_id' => 'AS'],
            ['name' => 'Bulgaria', 'continent_id' => 'EU'],
            ['name' => 'Burkina Faso', 'continent_id' => 'AF'],
            ['name' => 'Burundi', 'continent_id' => 'AF'],
            ['name' => 'Cambodia', 'continent_id' => 'AS'],
            ['name' => 'Cameroon', 'continent_id' => 'AF'],
            ['name' => 'Canada', 'continent_id' => 'NA'],
            ['name' => 'Cape Verde', 'continent_id' => 'AF'],
            ['name' => 'Central African Republic', 'continent_id' => 'AF'],
            ['name' => 'Chad', 'continent_id' => 'AF'],
            ['name' => 'Chile', 'continent_id' => 'SA'],
            ['name' => 'China', 'continent_id' => 'AS'],
            ['name' => 'Colombia', 'continent_id' => 'SA'],
            ['name' => 'Comoros', 'continent_id' => 'AF'],
            ['name' => 'Congo', 'continent_id' => 'AF'],
            ['name' => 'Costa Rica', 'continent_id' => 'NA'],
            ['name' => 'Croatia', 'continent_id' => 'EU'],
            ['name' => 'Cuba', 'continent_id' => 'NA'],
            ['name' => 'Cyprus', 'continent_id' => 'EU'],
            ['name' => 'Czech Republic', 'continent_id' => 'EU'],
            ['name' => 'Denmark', 'continent_id' => 'EU'],
            ['name' => 'Djibouti', 'continent_id' => 'AF'],
            ['name' => 'Dominica', 'continent_id' => 'NA'],
            ['name' => 'Dominican Republic', 'continent_id' => 'NA'],
            ['name' => 'Ecuador', 'continent_id' => 'SA'],
            ['name' => 'Egypt', 'continent_id' => 'AF'],
            ['name' => 'El Salvador', 'continent_id' => 'NA'],
            ['name' => 'Equatorial Guinea', 'continent_id' => 'AF'],
            ['name' => 'Eritrea', 'continent_id' => 'AF'],
            ['name' => 'Estonia', 'continent_id' => 'EU'],
            ['name' => 'Eswatini', 'continent_id' => 'AF'],
            ['name' => 'Ethiopia', 'continent_id' => 'AF'],
            ['name' => 'Fiji', 'continent_id' => 'OC'],
            ['name' => 'Finland', 'continent_id' => 'EU'],
            ['name' => 'France', 'continent_id' => 'EU'],
            ['name' => 'Gabon', 'continent_id' => 'AF'],
            ['name' => 'Gambia', 'continent_id' => 'AF'],
            ['name' => 'Georgia', 'continent_id' => 'AS'],
            ['name' => 'Germany', 'continent_id' => 'EU'],
            ['name' => 'Ghana', 'continent_id' => 'AF'],
            ['name' => 'Greece', 'continent_id' => 'EU'],
            ['name' => 'Grenada', 'continent_id' => 'NA'],
            ['name' => 'Guatemala', 'continent_id' => 'NA'],
            ['name' => 'Guinea', 'continent_id' => 'AF'],
            ['name' => 'Guinea-Bissau', 'continent_id' => 'AF'],
            ['name' => 'Guyana', 'continent_id' => 'SA'],
            ['name' => 'Haiti', 'continent_id' => 'NA'],
            ['name' => 'Honduras', 'continent_id' => 'NA'],
            ['name' => 'Hungary', 'continent_id' => 'EU'],
            ['name' => 'Iceland', 'continent_id' => 'EU'],
            ['name' => 'India', 'continent_id' => 'AS'],
            ['name' => 'Indonesia', 'continent_id' => 'AS'],
            ['name' => 'Iran', 'continent_id' => 'AS'],
            ['name' => 'Iraq', 'continent_id' => 'AS'],
            ['name' => 'Ireland', 'continent_id' => 'EU'],
            ['name' => 'Israel', 'continent_id' => 'AS'],
            ['name' => 'Italy', 'continent_id' => 'EU'],
            ['name' => 'Jamaica', 'continent_id' => 'NA'],
            ['name' => 'Japan', 'continent_id' => 'AS'],
            ['name' => 'Jordan', 'continent_id' => 'AS'],
            ['name' => 'Kazakhstan', 'continent_id' => 'AS'],
            ['name' => 'Kenya', 'continent_id' => 'AF'],
            ['name' => 'Kiribati', 'continent_id' => 'OC'],
            ['name' => 'Kuwait', 'continent_id' => 'AS'],
            ['name' => 'Kyrgyzstan', 'continent_id' => 'AS'],
            ['name' => 'Laos', 'continent_id' => 'AS'],
            ['name' => 'Latvia', 'continent_id' => 'EU'],
            ['name' => 'Lebanon', 'continent_id' => 'AS'],
            ['name' => 'Lesotho', 'continent_id' => 'AF'],
            ['name' => 'Liberia', 'continent_id' => 'AF'],
            ['name' => 'Libya', 'continent_id' => 'AF'],
            ['name' => 'Liechtenstein', 'continent_id' => 'EU'],
            ['name' => 'Lithuania', 'continent_id' => 'EU'],
            ['name' => 'Luxembourg', 'continent_id' => 'EU'],
            ['name' => 'Madagascar', 'continent_id' => 'AF'],
            ['name' => 'Malawi', 'continent_id' => 'AF'],
            ['name' => 'Malaysia', 'continent_id' => 'AS'],
            ['name' => 'Maldives', 'continent_id' => 'AS'],
            ['name' => 'Mali', 'continent_id' => 'AF'],
            ['name' => 'Malta', 'continent_id' => 'EU'],
            ['name' => 'Marshall Islands', 'continent_id' => 'OC'],
            ['name' => 'Mauritania', 'continent_id' => 'AF'],
            ['name' => 'Mauritius', 'continent_id' => 'AF'],
            ['name' => 'Mexico', 'continent_id' => 'NA'],
            ['name' => 'Micronesia', 'continent_id' => 'OC'],
            ['name' => 'Moldova', 'continent_id' => 'EU'],
            ['name' => 'Monaco', 'continent_id' => 'EU'],
            ['name' => 'Mongolia', 'continent_id' => 'AS'],
            ['name' => 'Montenegro', 'continent_id' => 'EU'],
            ['name' => 'Morocco', 'continent_id' => 'AF'],
            ['name' => 'Mozambique', 'continent_id' => 'AF'],
            ['name' => 'Myanmar', 'continent_id' => 'AS'],
            ['name' => 'Namibia', 'continent_id' => 'AF'],
            ['name' => 'Nauru', 'continent_id' => 'OC'],
            ['name' => 'Nepal', 'continent_id' => 'AS'],
            ['name' => 'Netherlands', 'continent_id' => 'EU'],
            ['name' => 'New Zealand', 'continent_id' => 'OC'],
            ['name' => 'Nicaragua', 'continent_id' => 'NA'],
            ['name' => 'Niger', 'continent_id' => 'AF'],
            ['name' => 'Nigeria', 'continent_id' => 'AF'],
            ['name' => 'North Korea', 'continent_id' => 'AS'],
            ['name' => 'North Macedonia', 'continent_id' => 'EU'],
            ['name' => 'Norway', 'continent_id' => 'EU'],
            ['name' => 'Oman', 'continent_id' => 'AS'],
            ['name' => 'Pakistan', 'continent_id' => 'AS'],
            ['name' => 'Palau', 'continent_id' => 'OC'],
            ['name' => 'Panama', 'continent_id' => 'NA'],
            ['name' => 'Papua New Guinea', 'continent_id' => 'OC'],
            ['name' => 'Paraguay', 'continent_id' => 'SA'],
            ['name' => 'Peru', 'continent_id' => 'SA'],
            ['name' => 'Philippines', 'continent_id' => 'AS'],
            ['name' => 'Poland', 'continent_id' => 'EU'],
            ['name' => 'Portugal', 'continent_id' => 'EU'],
            ['name' => 'Qatar', 'continent_id' => 'AS'],
            ['name' => 'Romania', 'continent_id' => 'EU'],
            ['name' => 'Russia', 'continent_id' => 'EU'],
            ['name' => 'Rwanda', 'continent_id' => 'AF'],
            ['name' => 'Saint Kitts and Nevis', 'continent_id' => 'NA'],
            ['name' => 'Saint Lucia', 'continent_id' => 'NA'],
            ['name' => 'Saint Vincent and the Grenadines', 'continent_id' => 'NA'],
            ['name' => 'Samoa', 'continent_id' => 'OC'],
            ['name' => 'San Marino', 'continent_id' => 'EU'],
            ['name' => 'Sao Tome and Principe', 'continent_id' => 'AF'],
            ['name' => 'Saudi Arabia', 'continent_id' => 'AS'],
            ['name' => 'Senegal', 'continent_id' => 'AF'],
            ['name' => 'Serbia', 'continent_id' => 'EU'],
            ['name' => 'Seychelles', 'continent_id' => 'AF'],
            ['name' => 'Sierra Leone', 'continent_id' => 'AF'],
            ['name' => 'Singapore', 'continent_id' => 'AS'],
            ['name' => 'Slovakia', 'continent_id' => 'EU'],
            ['name' => 'Slovenia', 'continent_id' => 'EU'],
            ['name' => 'Solomon Islands', 'continent_id' => 'OC'],
            ['name' => 'Somalia', 'continent_id' => 'AF'],
            ['name' => 'South Africa', 'continent_id' => 'AF'],
            ['name' => 'South Korea', 'continent_id' => 'AS'],
            ['name' => 'South Sudan', 'continent_id' => 'AF'],
            ['name' => 'Spain', 'continent_id' => 'EU'],
            ['name' => 'Sri Lanka', 'continent_id' => 'AS'],
            ['name' => 'Sudan', 'continent_id' => 'AF'],
            ['name' => 'Suriname', 'continent_id' => 'SA'],
            ['name' => 'Sweden', 'continent_id' => 'EU'],
            ['name' => 'Switzerland', 'continent_id' => 'EU'],
            ['name' => 'Syria', 'continent_id' => 'AS'],
            ['name' => 'Taiwan', 'continent_id' => 'AS'],
            ['name' => 'Tajikistan', 'continent_id' => 'AS'],
            ['name' => 'Tanzania', 'continent_id' => 'AF'],
            ['name' => 'Thailand', 'continent_id' => 'AS'],
            ['name' => 'Togo', 'continent_id' => 'AF'],
            ['name' => 'Tonga', 'continent_id' => 'OC'],
            ['name' => 'Trinidad and Tobago', 'continent_id' => 'NA'],
            ['name' => 'Tunisia', 'continent_id' => 'AF'],
            ['name' => 'Turkey', 'continent_id' => 'AS'],
            ['name' => 'Turkmenistan', 'continent_id' => 'AS'],
            ['name' => 'Tuvalu', 'continent_id' => 'OC'],
            ['name' => 'Uganda', 'continent_id' => 'AF'],
            ['name' => 'Ukraine', 'continent_id' => 'EU'],
            ['name' => 'United Arab Emirates', 'continent_id' => 'AS'],
            ['name' => 'United Kingdom', 'continent_id' => 'EU'],
            ['name' => 'United States', 'continent_id' => 'NA'],
            ['name' => 'Uruguay', 'continent_id' => 'SA'],
            ['name' => 'Uzbekistan', 'continent_id' => 'AS'],
            ['name' => 'Vanuatu', 'continent_id' => 'OC'],
            ['name' => 'Vatican City', 'continent_id' => 'EU'],
            ['name' => 'Venezuela', 'continent_id' => 'SA'],
            ['name' => 'Vietnam', 'continent_id' => 'AS'],
            ['name' => 'Yemen', 'continent_id' => 'AS'],
            ['name' => 'Zambia', 'continent_id' => 'AF'],
            ['name' => 'Zimbabwe', 'continent_id' => 'AF'],
        ];

        // Loop through the countries and insert them into the database
        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name' => $country['name'],
                'continent_id' => $country['continent_id'],
                'status' => 1, // Default status to active
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
